function plotDebrisTruth(simData)
%% NOTE: Code generated by Claude.ai and modified to suit needs
% (I hate making plots AI can do that for me in exchange for killing trees
% in the Amazon)
t       = simData.t;                  % [s], 1 x nTimes
x_truth = simData.truth.debris;       % [4 x nTimes]
t_min = t / 60;

%% Truth Circular Orbit (to check NL perturbations against)
theta = atan2(x_truth(3,1),x_truth(1,1));
mu = ModelParams('mu');
r0 = (x_truth(1,1)^2 + x_truth(3,1))^0.5;
omega = sqrt(mu/r0^3);
xCircular = getCircularOrbit(t, omega, r0, theta);

rE = ModelParams('rEarth');

%% Plot
% Raw States
plotData('Debris Truth States', x_truth, t_min);

% Error States
plotData('Debris Departure from Circular States', x_truth - xCircular, t_min);

% height vs time
figure('Name','Altitude vs Time');
plot(t_min, (x_truth(1,:).^2 + x_truth(3,:).^2).^0.5 - rE, 'LineWidth',1.4);
grid on;
xlabel('Time (min)');
ylabel('Altitude (km)');
title('Debris Altitude vs Time');


end

function plotData(dataName, data, t_min)
    stateLabels = { 'x  (km)',   ...
                'v_x  (km/s)', ...
                'y  (km)',   ...
                'v_y  (km/s)' };

    nStates = size(data, 1);   % 4

    %% Colors
    colors = [ 0.12  0.47  0.71 ;   % blue
               0.89  0.10  0.11 ;   % red
               0.20  0.63  0.17 ;   % green
               0.60  0.31  0.64 ];  % purple

    figure('Name', dataName);
    ax = [];
    for k = 1:nStates
        ax(end+1) = subplot(nStates, 1, k);
        hold on;
        plot(t_min, data(k,:), ...
             'Color', colors(k,:), ...
             'LineWidth', 1.4);
    
        ylabel(stateLabels{k}, 'FontSize', 11, 'Interpreter', 'tex');
        grid on;
        xlim([t_min(1) t_min(end)]);
    
        % Only show x-axis label on the bottom subplot
        if k == nStates
            xlabel('Time  (min)', 'FontSize', 12);
        else
            set(ax, 'XTickLabel', []);
        end
    
        % Tighten y-axis margins
        yl = ylim;
        pad = 0.05 * (yl(2) - yl(1));
        if pad > 0
            ylim([yl(1)-pad, yl(2)+pad]);
        end
    end
    
    linkaxes(ax,'x');
    
    % Shared title
    sgtitle(sprintf('%s vs. Time',dataName), 'FontSize', 14, 'FontWeight', 'bold');

end