function plotSimulation(simData, SKIP, fPlotTxRx)

    % CODE GENERATED BY CLAUDE.AI and modified to suit purposes
    
    nT      = simData.nTimes;
    nGPS    = simData.nGPS;
    nDebris = simData.nDebris;
    nRx = simData.nRx;
    t       = simData.t;


    stateToXY = @(state_4xN) deal( state_4xN(1,:), ...
                                state_4xN(3,:));


    
    %% ---- Pre-compute Cartesian truth positions -------------------------
    % Debris  (4 x nT x nDebris)
    xD = zeros(nT, nDebris);
    yD = zeros(nT, nDebris);
    for d = 1:nDebris
        [xD(:,d), yD(:,d)] = stateToXY(simData.truth.debris(:,:,d));
    end
    
    % Rx  (4 x nT x nRx)
    xR = zeros(nT, nRx);
    yR = zeros(nT, nRx);
    for r = 1:nRx
        [xR(:,r), yR(:,r)] = stateToXY(simData.truth.rx(:,:,r));
    end

    % GPS  (4 x nT x nGPS)
    xG = zeros(nT, nGPS);
    yG = zeros(nT, nGPS);
    for g = 1:nGPS
        [xG(:,g), yG(:,g)] = stateToXY(simData.truth.gps(:,:,g));
    end


    %% ---- Figure setup --------------------------------------------------
    fig = figure('Name','Simulation Animation');
    ax  = axes('Parent',fig);
    hold(ax,'on'); grid(ax,'on'); axis(ax,'equal');
    title(ax,'Orbital Simulation','FontSize',14);
    xlabel(ax,'X (km)');
    ylabel(ax,'Y (km)');

    % Colour palette
    COL_GPS    = [0.2  0.8  1.0];   % cyan-blue
    COL_DEBRIS = [1.0  0.4  0.1];   % orangecl
    COL_RX     = [0.4  1.0  0.4];   % green
    COL_LINK_GD = [0.0  0.0  0.0];  % black  GPS->Debris
    COL_LINK_DR = [1.0  0.3  0.8];  % magenta Debris->Rx
    COL_LINK_GR = [0.4  0.7  1.0];  % light-blue GPS->Rx
    
    
    
    % ---- Static: Earth circle (radius 6371 km) ----------------------------
    th_earth = linspace(0, 2*pi, 360);
    plot(ax, 6371*cos(th_earth), 6371*sin(th_earth), ...
         'Color',[0.2 0.5 1.0],'LineWidth',1.5);
    
    % ---- Trails (line objects updated each frame) -------------------------
    TRAIL = 2000;   % number of steps to show in trail
    h_trailD = gobjects(nDebris,1);
    for d = 1:nDebris
         h_trailD(d) = plot(ax, NaN, NaN, '-', 'Color', [COL_DEBRIS 0.35], 'LineWidth',1);
    end
    h_trailR = gobjects(nRx,1);
    for r = 1:nRx
         h_trailR(r) = plot(ax, NaN, NaN, '-', 'Color', [COL_RX     0.35], 'LineWidth',1);
    end
    h_trailG = gobjects(nGPS,1);
    for g = 1:nGPS
        h_trailG(g) = plot(ax, NaN, NaN, '-', 'Color', [COL_GPS 0.35], 'LineWidth',1);
    end
    
    % ---- Link lines (GPS->Debris, Debris->Rx, GPS->Rx) -------------------
    % Pre-allocate one line per GPS for GPS->Debris links
    h_linkGD = gobjects(nGPS,1);
    for g = 1:nGPS
        h_linkGD(g) = plot(ax, NaN, NaN, '--', 'Color', COL_LINK_GD, 'LineWidth',1.2);
    end
    h_linkDR = gobjects(nRx,1);
    for r = 1:nRx
        h_linkDR(r) = plot(ax, NaN, NaN, '--', 'Color', COL_LINK_DR, 'LineWidth',1.2);
    end
    h_linkGR = gobjects(nRx*nGPS,1);
    for rg = 1:nRx*nGPS
        h_linkGR(rg) = plot(ax, NaN, NaN, '--', 'Color', COL_LINK_GR, 'LineWidth',1.2);
    end
    
    % ---- Markers ----------------------------------------------------------
    % ASSUMING 1 DEBRIS FOR NOW
    h_debris = plot(ax, NaN, NaN, 'o', 'MarkerSize', 8, ...
                    'MarkerFaceColor', COL_DEBRIS, 'MarkerEdgeColor','w','LineWidth',0.8);

    h_rx    = gobjects(nRx,1);
    for r = 1:nRx
        h_rx(r) = plot(ax, NaN, NaN, 'd', 'MarkerSize', 9, ...
                    'MarkerFaceColor', COL_RX,     'MarkerEdgeColor','w','LineWidth',0.8);
    end
    h_gps    = gobjects(nGPS,1);
    for g = 1:nGPS
        h_gps(g) = plot(ax, NaN, NaN, '^', 'MarkerSize', 9, ...
                        'MarkerFaceColor', COL_GPS, 'MarkerEdgeColor','w','LineWidth',0.8);
    end
    
    % ---- Legend -----------------------------------------------------------
    legend(ax, [h_debris, h_rx(1), h_gps(1), h_linkGD(1), h_linkDR(1), h_linkGR(1)], ...
           {'Debris','Rx','GPS','GPS→Debris link','Debris→Rx link','GPS→Rx link'}, ...
            'Location','northeast');
    % legend(ax, [h_debris, h_rx(1), h_gps(1)], ...
    %        {'Debris','Rx','GPS'}, ...
    %         'Location','northeast');

    % ---- Time label -------------------------------------------------------
    h_time = text(ax, 0.02, 0.97, '', 'Units','normalized', ...
                  'FontSize',11,'VerticalAlignment','top');
    
    % ---- Axis limits (set from full trajectory) ---------------------------
    allX = [xD(:)', xR(:)', xG(:)'];
    allY = [yD(:)', yR(:)', yG(:)'];
    pad  = 2000;
    xlim(ax, [min(allX)-pad, max(allX)+pad]);
    ylim(ax, [min(allY)-pad, max(allY)+pad]);
    
    %% ---- Animation loop --------------------------------------------------
      % render every N-th time step (increase for speed, decrease for smoothness)
    
    for k = 1:SKIP:nT
    
        %-- Trails
        i0 = max(1, k-TRAIL);
        set(h_trailD, 'XData', xD(i0:k),   'YData', yD(i0:k));
        for r = 1:nRx
            set(h_trailR(r), 'XData', xR(i0:k,r),   'YData', yR(i0:k,r));
        end
        for g = 1:nGPS
            set(h_trailG(g), 'XData', xG(i0:k,g), 'YData', yG(i0:k,g));
        end
    
        %-- Markers
        set(h_debris, 'XData', xD(k), 'YData', yD(k));

        for r = 1:nRx
            set(h_rx(r),     'XData', xR(k,r), 'YData', yR(k,r));
        end
    
        for g = 1:nGPS
            set(h_gps(g), 'XData', xG(k,g), 'YData', yG(k,g));
        end
        if fPlotTxRx
            %-- GPS->Debris links  (msgs.debris cell at time k)
            % msgs.debris is a 1xnT cell array; each cell holds a struct array (may be empty)
            % Access: debrisMsgs = cell contents; debrisMsgs(m).gps.id for m-th message
            debrisMsgs = simData.msgs.debris{k};   % struct array or [] for this timestep
            activeGPS_debris = false(nGPS,1);
            if ~isempty(debrisMsgs)
                for m = 1:numel(debrisMsgs)
                    gid = debrisMsgs{m}.gps.id;
                    activeGPS_debris(gid) = true;    
                end
            end
            for g = 1:nGPS
                if activeGPS_debris(g)
                    set(h_linkGD(g), 'XData', [xG(k,g), xD(k)], 'YData', [yG(k,g), yD(k)]);
                else
                    set(h_linkGD(g), 'XData', NaN, 'YData', NaN);
                end
            end
        
            %-- Debris->Rx and GPS->Rx links  (msgs.rx cell at time k)
            rxMsgs = simData.msgs.rx{k};
            activeRx_debris = false(nRx,1);
            activeRx_gps = false(nRx,nGPS);
            if ~isempty(rxMsgs)
                for m = 1:numel(rxMsgs)
                    rxId = rxMsgs{m}.rx.id;
                    activeRx_debris(rxId) = true;
    
                    gpsId = rxMsgs{m}.gps.id;
                    activeRx_gps(rxId,gpsId) = rxMsgs{m}.gps.rxToGpsLineOfSight;
                end
    
                for r = 1:nRx
                    if activeRx_debris(r)
                        set(h_linkDR(r), 'XData', [xR(k,r), xD(k)], 'YData', [yR(k,r), yD(k)]);
                    else
                        set(h_linkDR(r), 'XData', NaN, 'YData', NaN);
                    end
    
                    for g = 1:nGPS
                        if activeRx_gps(r,g)
                            set(h_linkGR(r*g),'XData', [xR(k,r), xG(k,g)], 'YData', [yR(k,r), yG(k,g)]);
                        else
                            set(h_linkGR(r*g), 'XData', NaN, 'YData', NaN);
                        end
                    end
                end
            end
        end
        
        %-- Time label
        set(h_time, 'String', sprintf('t = %.1f s', t(k)));
        % axis equal;
        drawnow limitrate;
    end
end