function Jac_H = compute_H_matrix(in1,in2,in3,fT,c)
%compute_H_matrix
%    Jac_H = compute_H_matrix(IN1,IN2,IN3,fT,C)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Apr-2026 16:44:03

x = in1(1,:);
x_dot = in1(3,:);
xg = in2(1,:);
xg_dot = in2(3,:);
xr = in3(1,:);
xr_dot = in3(3,:);
y = in1(2,:);
y_dot = in1(4,:);
yg = in2(2,:);
yg_dot = in2(4,:);
yr = in3(2,:);
yr_dot = in3(4,:);
t2 = 1.0./c;
t3 = -xg;
t4 = -xg_dot;
t5 = -xr;
t6 = -xr_dot;
t7 = -yg;
t8 = -yg_dot;
t9 = -yr;
t10 = -yr_dot;
t11 = t3+x;
t12 = t5+x;
t13 = t4+x_dot;
t14 = t6+x_dot;
t15 = t7+y;
t16 = t9+y;
t17 = t8+y_dot;
t18 = t10+y_dot;
t19 = abs(t11);
t20 = abs(t12);
t21 = abs(t15);
t22 = abs(t16);
t23 = sign(t11);
t24 = sign(t12);
t25 = sign(t15);
t26 = sign(t16);
t27 = t19.^2;
t28 = t20.^2;
t29 = t21.^2;
t30 = t22.^2;
t31 = t27+t29;
t32 = t28+t30;
t33 = 1.0./sqrt(t31);
t35 = 1.0./sqrt(t32);
t34 = t33.^3;
t36 = t35.^3;
Jac_H = [-fT.*t2.*(-t13.*t33-t14.*t35+t11.*t13.*t19.*t23.*t34+t12.*t14.*t20.*t24.*t36+t15.*t17.*t19.*t23.*t34+t16.*t18.*t20.*t24.*t36),-fT.*t2.*(-t17.*t33-t18.*t35+t11.*t13.*t21.*t25.*t34+t12.*t14.*t22.*t26.*t36+t15.*t17.*t21.*t25.*t34+t16.*t18.*t22.*t26.*t36),fT.*t2.*(t11.*t33+t12.*t35),fT.*t2.*(t15.*t33+t16.*t35)];
end
